[package]
name = "reth-node-telos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
antelope-client.workspace = true

reth.workspace = true
reth-primitives.workspace = true
reth-auto-seal-consensus.workspace = true
reth-basic-payload-builder.workspace = true
reth-beacon-consensus.workspace = true
reth-chainspec.workspace = true
reth-ethereum-payload-builder.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-evm-ethereum.workspace = true
reth-network.workspace = true
reth-node-api.workspace = true
reth-node-builder.workspace = true
reth-node-types.workspace = true
reth-node-ethereum.workspace = true
reth-payload-builder.workspace = true
reth-provider.workspace = true
reth-rpc.workspace = true
reth-stages.workspace = true
reth-telos-rpc.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true
reth-telos-rpc-engine-api.workspace = true

clap.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.122"
tokio = "1.39.2"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[features]
telos = [
    "reth/telos",
    "reth-basic-payload-builder/telos",
    "reth-beacon-consensus/telos",
    "reth-chainspec/telos",
    "reth-ethereum-engine-primitives/telos",
    "reth-ethereum-payload-builder/telos",
    "reth-node-builder/telos",
    "reth-payload-builder/telos",
    "reth-primitives/telos",
    "reth-provider/telos",
    "reth-rpc/telos",
    "reth-stages/telos",
    "reth-transaction-pool/telos",
]

[dev-dependencies]
alloy-consensus.workspace = true
alloy-contract = "0.4.2"
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-network.workspace = true
alloy-rpc-client.workspace = true
alloy-rpc-types.workspace = true
alloy-signer-local.workspace = true
alloy-sol-types.workspace = true
alloy-transport-http.workspace = true
reqwest.workspace = true

reth.workspace = true
reth-chainspec.workspace = true
reth-e2e-test-utils.workspace = true
eyre.workspace = true

telos-consensus-client = { git = "https://github.com/telosnetwork/telos-consensus-client", rev = "f8ecbe1aeea57911c9fbefdddf49efa92d8472ce" }
telos-translator-rs = { git = "https://github.com/telosnetwork/telos-consensus-client", rev = "f8ecbe1aeea57911c9fbefdddf49efa92d8472ce" }
#telos-consensus-client = { path = "../../../../telos-consensus-client/client" }
#telos-translator-rs = { path = "../../../../telos-consensus-client/translator" }

env_logger = "0.11.5"
testcontainers = "0.21.1"
derive_more.workspace = true

